version: '3'

services:
  api:
    image: api-roles
    build:
      context: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
