---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/memberships/{id}/role":
    parameters:
    - name: id
      in: path
      description: Membership ID
      required: true
      schema:
        type: string
    get:
      summary: Fetch membership's role
      tags:
      - Memberships
      responses:
        '200':
          description: Membership found
        '404':
          description: Membership not found
  "/api/memberships":
    post:
      summary: Creates a membership
      tags:
      - Memberships
      parameters: []
      responses:
        '201':
          description: Membership created
        '422':
          description: Membership not created due to invalid attributes or error
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                role_id:
                  type: string
                user_id:
                  type: string
                team_id:
                  type: string
              required:
              - role_id
              - user_id
              - team_id
  "/api/memberships/{id}":
    parameters:
    - name: id
      in: path
      description: Membership ID
      required: true
      schema:
        type: string
    get:
      summary: Fetch membership
      tags:
      - Memberships
      responses:
        '200':
          description: Membership found
        '404':
          description: Membership not found
  "/api/roles/{id}/memberships":
    parameters:
    - name: id
      in: path
      description: ID of Role
      required: true
      schema:
        type: string
    get:
      summary: Fetch role's membership
      tags:
      - Roles
      responses:
        '200':
          description: Returns related membership
        '404':
          description: Role not found
  "/api/roles":
    get:
      summary: List roles
      tags:
      - Roles
      parameters:
      - name: page
        in: query
        description: Page number
        required: false
        schema:
          type: integer
      - name: per
        in: query
        description: Items per page
        required: false
        schema:
          type: integer
      responses:
        '200':
          description: successful
    post:
      summary: Create a role
      tags:
      - Roles
      parameters: []
      responses:
        '201':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/roles/{id}":
    parameters:
    - name: id
      in: path
      description: Role ID
      required: true
      schema:
        type: string
    get:
      summary: Fetch a single role
      tags:
      - Roles
      responses:
        '200':
          description: Role found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  create_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - name
        '404':
          description: Role not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
